config/routes.rb
Rails.application.routes.draw do
  # User model planned for clients feature
  devise_for :users
  devise_for :milk_admins, skip: [ :registrations ]

  # root for milk admin
  authenticated :milk_admin do
    root to: "milk_admin#dashboard", as: :milk_admin_root
  end

  # Admin Routes
  namespace :milk_admin do
    resource :profile, only: [ :show, :edit, :update ]
    resources :contacts, only: [ :destroy ]
    resources :blog_categories

    # Dashboard routes
    get "blogs/dashboard", to: "blogs#dashboard", as: :blogs_dashboard
    # get "projects/dashboard", to: "projects#dashboard", as: :projects_dashboard
    get "pills/dashboard", to: "pills#dashboard", as: :pills_dashboard
    get "songs/dashboard", to: "songs#dashboard", as: :songs_dashboard
    get "messages/dashboard", to: "messages#dashboard", as: :messages_dashboard

    resources :blogs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
    end

    resources :projects, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
      resources :tasks
    end

    resources :songs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
        delete :destroy_file
      end
    end

    resources :pills, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Public Blog Routes
  resources :blogs, only: [ :index, :show ], controller: "blogs", param: :slug do
    collection do
      get "feature"  # This creates the route for /blogs/feature
      get "categories/:id", action: :index, as: :category # adds category_blogs_path
    end
  end

  # Public Zuke routes
  resources :zuke, only: [ :index ], controller: "zuke" do
    collection do
      get "music", to: "zuke#music", as: :music_list  # This creates the route for /zuke/music
      get "artists", to: "zuke#artists", as: :music_artists
      get "albums", to: "zuke#albums", as: :music_albums
      get "genres", to: "zuke#genres", as: :music_genres
      get "about", to: "zuke#about", as: :music_about
    end
  end


  # root for hermits
  get "hermit-plus", to: "hermit_plus#landing", as: :hermits
  # Public Salt and Tar routes
  resources :salt_and_tar, only: [ :index ], path: "salt-and-tar", controller: "salt_and_tar" do
    collection do
      get "archive", to: "salt_and_tar#archive", as: :archive  # /salt-and-tar/archive
    end
  end
  # root for eastbounds
  get "eastbound", to: "eastbounds#index", as: :eastbound
  # root for public route, copywriter
  get "copywriter", to: "copywriter#index", as: :copywriter


  get "info", to: "static_pages#info", as: :info
  get "info/welcome", to: "info#welcome"
  get "info/about_me", to: "info#about_me"
  get "info/skills", to: "info#skills"
  get "info/erudition", to: "info#erudition"

  resources :contacts, only: [ :new, :create ]
  resources :projects, only: [ :index ]
  resources :skills, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @featured_projects = Project.where(featured: true).order(updated_at: :desc).pluck(:short_title, :short_description).map do |title, description|
      {
        title: title,
        description: description,
        path: "/#{title.parameterize}"
      }
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="max-w-5xl mx-auto w-full px-3">
  <%= render "shared/main_nav" %>
  <section>
    <!-- Welcome Hero with navigation -->
    <div class="flex flex-col-reverse md:flex-row justify-center items-start md:items-stretch gap-2 mt-4 mb-2">
      <%# 1. Right side info frame %>
      <turbo-frame id="info" class="flex flex-col justify-start items-start w-full md:w-3/4">
        <%= image_tag "RogueMediaLab-intro.png", 
                  alt: "Welcome to the lab", 
                  class: "border-2 border-gray-800 rounded-lg w-full lg:max-w-[700px] max-h-[525px] overflow-hidden" %>
      </turbo-frame>
      <%# 2. Left side info sidebar %>
      <div id="info-nav" class="hidden md:flex flex-col w-full md:w-1/4">
        <h2 class="text-3xl font-bold dark:text-milk-light text-base-dark">Info</h2>
        <hr class="my-4 w-full dark:border-white border-base-dark">
        <%= info_nav_link "Welcome", info_welcome_path, data: { turbo_frame: "info" } %>
        <%= info_nav_link "About Me", info_about_me_path, data: { turbo_frame: "info" } %>
        <%= info_nav_link "Skills", skills_path, data: { turbo_frame: "info" } %>
        <%= info_nav_link "Blog", blogs_path %>
        <%= info_nav_link "Projects", projects_path, data: { turbo_frame: "info" } %>

        <%# 2. Use proper path helpers for robust links %>
        <%= info_nav_link "Contact", new_contact_path, data: { turbo_frame: "info" } %>
        <%= info_nav_link "Erudition", info_erudition_path, data: { turbo_frame: "info" } %>
        <%= info_nav_link "Code - GitHub", "https://github.com/Developer3027", target: "_blank" %>
      </div>
    </div>
    <!-- Featured projects -->
    <div class="my-6">
      <h2 class="text-3xl font-bold dark:text-milk-light text-base-dark">Featured</h2>
      <hr class="my-4 w-full dark:border-white border-base-dark">
        <div class="flex justify-between items-center flex-wrap w-full my-2">
          <%= render partial: "shared/project_card", collection: @featured_projects, as: :project_card %>
      </div>
    </div>
  </section>
</div>

app/views/static_pages/oldIndex.html.erb
<div class="flex flex-col justify-around items-center h-full w-full min-h-screen mt-4" data-controller="dark-mode">
  <!-- top link -->
  <div class="flex justify-evenly items-center w-full lg:max-w-4xl">
    <!-- dark mode toggle -->
    <%= render "shared/darkmode_toggle" %>
    <div class="flex flex-col">
      <div>
        <%= link_to "MILK Blog", root_path, class: "text-3xl font-extrabold text-milk-dark dark:text-milk-light" %>
      </div>
      <div class="flex justify-between items-center mt-4">
        <!-- github icon -->
        <svg class="w-6 h-6 text-base-dark dark:text-milk-light" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M12.006 2a9.847 9.847 0 0 0-6.484 2.44 10.32 10.32 0 0 0-3.393 6.17 10.48 10.48 0 0 0 1.317 6.955 10.045 10.045 0 0 0 5.4 4.418c.504.095.683-.223.683-.494 0-.245-.01-1.052-.014-1.908-2.78.62-3.366-1.21-3.366-1.21a2.711 2.711 0 0 0-1.11-1.5c-.907-.637.07-.621.07-.621.317.044.62.163.885.346.266.183.487.426.647.71.135.253.318.476.538.655a2.079 2.079 0 0 0 2.37.196c.045-.52.27-1.006.635-1.37-2.219-.259-4.554-1.138-4.554-5.07a4.022 4.022 0 0 1 1.031-2.75 3.77 3.77 0 0 1 .096-2.713s.839-.275 2.749 1.05a9.26 9.26 0 0 1 5.004 0c1.906-1.325 2.74-1.05 2.74-1.05.37.858.406 1.828.101 2.713a4.017 4.017 0 0 1 1.029 2.75c0 3.939-2.339 4.805-4.564 5.058a2.471 2.471 0 0 1 .679 1.897c0 1.372-.012 2.477-.012 2.814 0 .272.18.592.687.492a10.05 10.05 0 0 0 5.388-4.421 10.473 10.473 0 0 0 1.313-6.948 10.32 10.32 0 0 0-3.39-6.165A9.847 9.847 0 0 0 12.007 2Z" clip-rule="evenodd"/>
        </svg>
        <!-- gitlab icon -->
        <svg class="w-6 h-6 text-base-dark dark:text-milk-light" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path fill="currentColor" d="m20.7011 10.1255-.0253-.0672-2.4501-6.63953c-.0498-.13013-.1381-.24053-.2521-.31534-.1141-.07354-.2472-.10896-.3812-.10147-.1341.00748-.2628.05751-.3686.14332-.1047.08828-.1806.2079-.2175.34259l-1.6543 5.2556H8.65334l-1.65429-5.2556c-.03588-.13542-.11197-.25564-.21745-.34356-.10584-.08582-.23449-.13584-.36857-.14333-.13409-.00748-.26716.02794-.38125.10148-.11376.07511-.20195.18541-.25213.31534l-2.45472 6.6367-.02437.0671c-.35269.9569-.39623 2.007-.12404 2.9918.27219.9849.84535 1.8511 1.63305 2.4682l.00844.0068.02249.0166 3.73223 2.9022 1.84647 1.4512 1.1247.8817c.1316.1037.2922.1599.4574.1599.1652 0 .3258-.0562.4574-.1599l1.1247-.8817 1.8464-1.4512 3.7548-2.9198.0093-.0077c.786-.6172 1.3578-1.4826 1.6296-2.4661.2717-.9835.2288-2.0321-.1224-2.9881Z"/>
        </svg>
        <!-- linked in icon -->
        <svg class="w-6 h-6 text-base-dark dark:text-milk-light" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path fill-rule="evenodd" d="M12.51 8.796v1.697a3.738 3.738 0 0 1 3.288-1.684c3.455 0 4.202 2.16 4.202 4.97V19.5h-3.2v-5.072c0-1.21-.244-2.766-2.128-2.766-1.827 0-2.139 1.317-2.139 2.676V19.5h-3.19V8.796h3.168ZM7.2 6.106a1.61 1.61 0 0 1-.988 1.483 1.595 1.595 0 0 1-1.743-.348A1.607 1.607 0 0 1 5.6 4.5a1.601 1.601 0 0 1 1.6 1.606Z" clip-rule="evenodd"/>
          <path d="M7.2 8.809H4V19.5h3.2V8.809Z"/>
        </svg>
      </div>
      <div class="hidden md:flex justify-evenly items-center mt-4">
        <!-- Fiverr Icon -->
        <svg class="w-[21px] h-6 text-base-dark dark:text-milk-light" width="21" height="22" viewBox="0 0 21 22" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M17.875 17.875V6.875H6.875V6.1875C6.875 5.0501 7.8001 4.125 8.9375 4.125H11V0H8.9375C7.2971 0.00203759 5.72447 0.654587 4.56453 1.81453C3.40459 2.97447 2.75204 4.5471 2.75 6.1875V6.875H0V11H2.75V17.875H0V22H9.625V17.875H6.875V11H13.7885V17.875H11V22H20.625V17.875H17.875Z"/>
          <path d="M15.8125 4.125C16.9516 4.125 17.875 3.20159 17.875 2.0625C17.875 0.923413 16.9516 0 15.8125 0C14.6734 0 13.75 0.923413 13.75 2.0625C13.75 3.20159 14.6734 4.125 15.8125 4.125Z"/>
        </svg>
        <!-- UpWork Icon-->
        <svg class="w-7 h-6 text-base-dark dark:text-milk-light" width="28" height="22" viewBox="0 0 28 22" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
          <path d="M21.6556 12.4948C20.3702 12.4948 19.1628 11.8936 18.0691 10.9093L18.3333 9.5207L18.3421 9.46542C18.5835 7.99048 19.3308 5.51091 21.6547 5.51091C23.3959 5.51091 24.8081 7.07701 24.8081 9.00577C24.8081 10.9297 23.395 12.4958 21.6547 12.4958L21.6556 12.4948ZM21.6556 1.97435C18.6938 1.97435 16.3917 4.10579 15.4581 7.61617C14.0363 5.24715 12.9513 2.39908 12.3231 0H9.13296V9.19681C9.12859 11.015 7.80213 12.4851 6.16156 12.49C4.52098 12.4851 3.19453 11.0102 3.19015 9.19681V0H0V9.19681C0 12.9642 2.76579 16.0508 6.16156 16.0508C9.56083 16.0508 12.3231 12.9651 12.3231 9.19681V7.65593C12.9426 9.08529 13.7038 10.5399 14.6287 11.8228L12.674 22H15.9368L17.3542 14.6156C18.594 15.4942 20.0202 16.0498 21.6564 16.0498C25.1563 16.0498 28 12.8779 28 9.00383C28 5.12496 25.1563 1.97338 21.6564 1.97338L21.6556 1.97435Z"/>
        </svg>
      </div>
    </div>
    <!-- Milk Admin sign in -->
    <%= link_to new_milk_admin_session_path do %>
      <%= image_tag "mug.svg", alt: "admin sign in" %>
    <% end %>
  </div>

  <!-- Mobile Only -->
  <div class="md:hidden flex flex-col w-full max-w-80">
    <div class="flex justify-between items-center w-full mt-4">
      <span>Info</span>
      <%= link_to "About", root_path, class: "my-3 text-milk-dark dark:text-milk-light" %>
    </div>
    <div class="text-right text-milk-dark dark:text-milk-light w-full my-3">
      <span>Tech Stacks</span>
    </div>
    <div class="text-right text-milk-dark dark:text-milk-light w-full my-3">
      <span>Build your project</span>
    </div>

    <div class="flex justify-between items-center w-full mt-4">
      <span>Employers</span>
      <%= link_to "Resume", root_path, class: "text-milk-dark dark:text-milk-light my-3" %>
    </div>

    <div class="flex justify-between items-center w-full mt-4">
      <span>Clients</span>
      <%= link_to "Log In", root_path, class: "text-milk-dark dark:text-milk-light my-3" %>
    </div>
    <div class="text-right text-milk-dark dark:text-milk-light w-full my-3">
      <span>Up Work</span>
    </div>
    <div class="text-right text-milk-dark dark:text-milk-light w-full my-3">
      <span>Fiverr</span>
    </div>

    <div class="flex justify-between items-center w-full mt-4">
      <span>Favorites</span>
      <%= link_to "Swabbie", swabbies_path, class: "text-milk-dark dark:text-milk-light my-3" %>
    </div>
    <%= link_to "Hermit Plus", hermits_path, class: "text-right text-milk-dark dark:text-milk-light w-full my-3" %>
    <%= link_to "East Bound", eastbound_path, class: "text-right text-milk-dark dark:text-milk-light w-full my-3" %>
    <%= link_to "Copywriter", copywriter_path, class: "text-right text-milk-dark dark:text-milk-light w-full my-3" %>
    <%= link_to "Projects", root_path, class: "text-right text-milk-dark dark:text-milk-light w-full my-3" %>

    <div class="w-24 mb-4">
      <%= image_tag "MILK8.png", alt: "Rails logo" %>
    </div>
  </div>
  <!-- center div -->
  <div class="flex flex-col md:flex-row justify-evenly items-center w-full lg:max-w-4xl">
    <!-- desktop upper menu -->
    <div class="hidden md:flex flex-col">
      <%= link_to "About Me", info_path + "#about-me", class: "font-medium my-2" %>
      <%= link_to "The Stacks", root_path, class: "font-medium my-2" %>
      <%= link_to "Projects", root_path, class: "font-medium my-2" %>
      <%= link_to "Code", root_path, class: "font-medium my-2" %>
    </div>
    <!-- logo -->
    <div class="hidden md:block">
      <%= image_tag "MILK8.png", alt: "Rails logo" %>
    </div>
    <!-- lower menu -->
    <div class="hidden md:flex flex-col">
      <%= link_to "Client", root_path, class: "font-medium my-2" %>
      <%= link_to "Employer", root_path, class: "font-medium my-2" %>
      <%= link_to "Discord", root_path, class: "font-medium my-6" %>
    </div>
  </div>
  <!-- project links -->
  <div class="hidden md:flex flex-col md:flex-row justify-evenly text-center w-full h-full lg:max-w-4xl text-2xl lg:text-3xl">
    <%= link_to "Swabbie", swabbies_path, class: "font-bold my-2 md:my-0" %>
    <%= link_to "EastBound", eastbound_path, class: "font-bold my-2 md:my-0" %>
    <%= link_to "Hermit Plus", hermits_path, class: "font-bold my-2 md:my-0" %>
    <%= link_to "Copywriter", copywriter_path, class: "font-bold my-2 md:my-0" %>
  </div>

</div>

app/views/static_pages/resume.html.erb
<h1 id = "welcome-to-milk-00">Welcome to MILK-00</h1><div>My name is Mason Roberts and known as Developer 3027 in all my code. I am an automotive technician during the day. This includes shop management and training employees as well as tending to the automotive needs of my customers. On my days off and in the evening, I am Developer 3027 and work on learning and growing as a web engineer.<br><br>
</div><h1 id="overview">Overview</h1><div>Over the past year, 2024, I focused on learning Ruby on Rails. I find the platform a joy to work with. Unlike other frameworks, Rails is the real deal with that one stop, full service functionality. I love that it's approach to the Model View Controller methodology (MVC) is so straight forward. I also love that with Turbo you can provide the same feel and style one may want from a framework like React. Rails provides for both the Frontend and Backend and includes a Object Relational Mapper (ORM) that ensures working with a relational database like PostgreSQL is a dream. Need to add a column to the database? Bam! Need to change it so the reference id can be false? Bam! Just create and run that migration.<br><br>
</div><h1 id="main-reason">Main Reason</h1><div>I have built this web app to demonstrate what I can do, not only in Rails, but as a developer and designer. I also wanted a few things for myself on the internet. I have several ideas that are in various stages of build in other frameworks. Here with Rails I have brought them all together in one place for everyone to enjoy. This has been a challenge for sure. Each project should look and feel like it is it's own site and all be managed from the central admin dashboard. In the end I want to be able to simply lift the site out of MILK and place it on it's own in the world, with minimal effort. What kind of projects am I talking about?<br><br>I have enjoyed the Hermits of Hermitcraft for many years. Season 8 was especially good and thought that they would benefit form there own spotlight. YouTube is an amazing platform and the Hermits have used it to great advantage, but I would have loved to had better, more organized, access to them.&nbsp;<br><br>I love Garret and Ruth of Salt and Tar. The boat they have built called Rediviva is just amazing. I always thought that they would have benefited from a bit of different functionality in there site. As with many content providers, they are spread across several different platforms. I would like to help all content providers out with that, but first, I built a site I think they would really enjoy. At the minimum, I will.<br><br>These are just a few of the projects I am working through. This blog is for telling the story of building such a thing, and maybe someone will learn from my experience. Welcome and enjoy your stay.</div>