config/routes.rb
Rails.application.routes.draw do
  # User model planned for clients feature
  devise_for :users
  devise_for :milk_admins, skip: [ :registrations ]

  # root for milk admin
  authenticated :milk_admin do
    root to: "milk_admin#dashboard", as: :milk_admin_root
  end

  # Admin Routes
  namespace :milk_admin do
    resource :profile, only: [ :show, :edit, :update ]
    resources :contacts, only: [ :destroy ]
    resources :blog_categories

    # Dashboard routes
    get "blogs/dashboard", to: "blogs#dashboard", as: :blogs_dashboard
    # get "projects/dashboard", to: "projects#dashboard", as: :projects_dashboard
    get "pills/dashboard", to: "pills#dashboard", as: :pills_dashboard
    get "songs/dashboard", to: "songs#dashboard", as: :songs_dashboard
    get "messages/dashboard", to: "messages#dashboard", as: :messages_dashboard

    resources :blogs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
    end

    resources :projects, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
      resources :tasks
    end

    resources :songs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
        delete :destroy_file
      end
    end

    resources :pills, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Public Blog Routes
  resources :blogs, only: [ :index, :show ], controller: "blogs", param: :slug do
    collection do
      get "feature"  # This creates the route for /blogs/feature
      get "categories/:id", action: :index, as: :category # adds category_blogs_path
    end
  end

  # Public Zuke routes
  resources :zuke, only: [ :index ], controller: "zuke" do
    collection do
      get "music", to: "zuke#music", as: :music_list  # This creates the route for /zuke/music
      get "artists", to: "zuke#artists", as: :music_artists
      get "albums", to: "zuke#albums", as: :music_albums
      get "genres", to: "zuke#genres", as: :music_genres
      get "about", to: "zuke#about", as: :music_about
    end
  end


  # root for hermits
  get "hermit-plus", to: "hermit_plus#landing", as: :hermits
  # Public Salt and Tar routes
  resources :salt_and_tar, only: [ :index ], path: "salt-and-tar", controller: "salt_and_tar" do
    collection do
      get "archive", to: "salt_and_tar#archive", as: :archive  # /salt-and-tar/archive
    end
  end
  # root for eastbounds
  get "eastbound", to: "eastbounds#index", as: :eastbound
  # root for public route, copywriter
  get "copywriter", to: "copywriter#index", as: :copywriter


  get "info", to: "static_pages#info", as: :info
  get "info/welcome", to: "info#welcome"
  get "info/about_me", to: "info#about_me"
  get "info/skills", to: "info#skills"
  get "info/erudition", to: "info#erudition"

  resources :contacts, only: [ :new, :create ]
  resources :projects, only: [ :index ]
  resources :skills, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#index"
end

app/helpers/sidebar_helper.rb
module SidebarHelper
  SIDEBAR_CONTROLLER = "music--sidebar".freeze

  def sidebar_link_to(name, path, icon_name, options = {})
    content_tag :li, class: "flex h-11 items-center rounded-xs p-1 hover:bg-[#FFC9A4]/50 transition-colors w-full",
                     data: { "#{SIDEBAR_CONTROLLER}-target": "link",
                     action: "click->#{SIDEBAR_CONTROLLER}#setActive" } do
      link_to path, class: "flex items-center w-full cursor-pointer", data: options[:data] || {} do
        concat icon(icon_name)
        concat content_tag(:span, name, class: "ms-3")
      end
    end
  end

  def icon(name)
    # Render SVG icons in icons folder, based on the name
    render "icons/#{name}"
  end

  # info links used in the main root
  def info_nav_link(name, path, options = {})
    # Default classes for the navigation links
    default_classes = "border dark:border-milk-light border-base-dark rounded-md p-2 w-full mb-4"

    # Merge default classes with any provided classes
    options[:class] = [ default_classes, options[:class] ].compact.join(" ")

    # Create the link
    link_to name, path, options
  end
end

app/views/sidebar/_index.html.erb
<button data-drawer-target="default-sidebar" data-drawer-toggle="default-sidebar" aria-controls="default-sidebar" type="button" class="inline-flex items-center p-2 mt-2 ms-3 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-hidden focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
   <span class="sr-only">Open sidebar</span>
   <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
   <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
   </svg>
</button>

<aside id="default-sidebar" class="fixed top-0 left-0 z-40 w-64 h-screen transition-transform -translate-x-full sm:translate-x-0" aria-label="Sidebar">
   <div class="h-full px-3 py-4 overflow-y-auto bg-gray-800">
      <ul class="space-y-2 font-medium text-gray-200">
         <%= render "sidebar/link", path: milk_admin_root_path, icon: render("sidebar/icons/home"), text: "Home" %>
         <%= render "sidebar/link", path: milk_admin_blogs_path, icon: render("sidebar/icons/menu"), text: "Blogs" %>
         <%= render "sidebar/link", path: milk_admin_songs_path, icon: render("sidebar/icons/menu"), text: "Songs" %>
         <%= render "sidebar/link", path: root_path, icon: render("sidebar/icons/menu"), text: "Resume" %>
         <%= render "sidebar/link", path: milk_admin_projects_path, icon: render("sidebar/icons/menu"), text: "Projects" %>
         <%= render "sidebar/link", path: milk_admin_pills_path, icon: render("sidebar/icons/menu"), text: "Pills" %>
         <%= render "sidebar/signout"%>
      </ul>
   </div>
</aside>

app/views/sidebar/_link.html.erb
<li>
  <a href="<%= path %>" class="flex items-center p-2 text-gray-200 rounded-lg bg-gray-700 hover:bg-sky-800 group">
    <%= icon %>
    <span class="flex-1 ml-3 whitespace-nowrap"><%= text %></span>
  </a>
</li>

app/views/sidebar/_signout.html.erb
<li>
  <a href="<%= destroy_milk_admin_session_path %>" data-turbo-method="delete" class="flex items-center p-2 text-gray-200 rounded-lg bg-gray-700 hover:bg-sky-800 group">
    <%= render "sidebar/icons/signout" %>
    <span class="flex-1 ml-3 whitespace-nowrap">Signout</span>
  </a>
</li>