config/routes.rb
Rails.application.routes.draw do
  # User model planned for clients feature
  devise_for :users
  devise_for :milk_admins, skip: [ :registrations ]

  # root for milk admin
  authenticated :milk_admin do
    root to: "milk_admin#dashboard", as: :milk_admin_root
  end

  # Admin Routes
  namespace :milk_admin do
    resource :profile, only: [ :show, :edit, :update ]
    resources :contacts, only: [ :destroy ]
    resources :blog_categories

    # Dashboard routes
    get "blogs/dashboard", to: "blogs#dashboard", as: :blogs_dashboard
    # get "projects/dashboard", to: "projects#dashboard", as: :projects_dashboard
    get "pills/dashboard", to: "pills#dashboard", as: :pills_dashboard
    get "songs/dashboard", to: "songs#dashboard", as: :songs_dashboard
    get "messages/dashboard", to: "messages#dashboard", as: :messages_dashboard

    resources :blogs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
    end

    resources :projects, only: [ :index, :show, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
      end
      resources :tasks
    end

    resources :songs, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      member do
        delete :destroy_image
        delete :destroy_file
      end
    end

    resources :pills, only: [ :index, :new, :create, :edit, :update, :destroy ]
  end

  # Public Blog Routes
  resources :blogs, only: [ :index, :show ], controller: "blogs", param: :slug do
    collection do
      get "feature"  # This creates the route for /blogs/feature
      get "categories/:id", action: :index, as: :category # adds category_blogs_path
    end
  end

  # Public Zuke routes
  resources :zuke, only: [ :index ], controller: "zuke" do
    collection do
      get "music", to: "zuke#music", as: :music_list  # This creates the route for /zuke/music
      get "artists", to: "zuke#artists", as: :music_artists
      get "albums", to: "zuke#albums", as: :music_albums
      get "genres", to: "zuke#genres", as: :music_genres
      get "about", to: "zuke#about", as: :music_about
    end
  end


  # root for hermits
  get "hermit-plus", to: "hermit_plus#landing", as: :hermits
  # Public Salt and Tar routes
  resources :salt_and_tar, only: [ :index ], path: "salt-and-tar", controller: "salt_and_tar" do
    collection do
      get "archive", to: "salt_and_tar#archive", as: :archive  # /salt-and-tar/archive
    end
  end
  # root for eastbounds
  get "eastbound", to: "eastbounds#index", as: :eastbound
  # root for public route, copywriter
  get "copywriter", to: "copywriter#index", as: :copywriter


  get "info", to: "static_pages#info", as: :info
  get "info/welcome", to: "info#welcome"
  get "info/about_me", to: "info#about_me"
  get "info/skills", to: "info#skills"
  get "info/erudition", to: "info#erudition"

  resources :contacts, only: [ :new, :create ]
  resources :projects, only: [ :index ]
  resources :skills, only: [ :index ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "static_pages#index"
end

app/controllers/milk_admin/blog_categories_controller.rb
class MilkAdmin::BlogCategoriesController < ApplicationController
  def new
    @blog_category = BlogCategory.new
  end

  def create
    @blog_category = BlogCategory.new(blog_category_params)

    if @blog_category.save
      redirect_to blog_categories_path, notice: "Category for Blog was successfully created."
    else
      render :new
    end
  end

  def update
    @blog_category = BlogCategory.find(params[:id])

    if @blog_category.update(blog_category_params)
      redirect_to blog_categories_path, notice: "Category for Blog was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @blog_category = BlogCategory.find(params[:id])
    @blog_category.destroy
    redirect_to categories_path, notice: "Category for Blog was successfully destroyed."
  end

  private

  def blog_category_params
    params.require(:blog_category).permit(:title, :description)
  end
end

app/controllers/milk_admin/blogs_controller.rb
# Blog Controller for Milk Admin
class MilkAdmin::BlogsController < ApplicationController
  # Ensure milk admin is logged in for CRUD actions
  before_action :authenticate_milk_admin!
  # Set blog for methods that need it
  before_action :set_blog, only: [ :edit, :update, :destroy, :destroy_image ]
  # Set blog categories for methods that need it
  before_action :set_blog_categories, only: [ :new, :create, :edit, :update ]

  # GET /milk_admin/blogs
  #
  # Returns all blogs. The `format.html` response is the default view for
  # this controller and is used for the index page of the milk admin dashboard.
  # The `format.json` response is used by the JavaScript frontend to populate the data tables.
  def index
    @featured_blog = Blog.where(featured: true).first
    @blogs = Blog.all.sorted

    if @featured_blog.present?
      @blogs = @blogs.where.not(id: @featured_blog.id)
    end


    respond_to do |format|
      format.html
      # format.json { render json: @blogs.as_json(
      #   only: [ :id, :title, :content, :published_at, :image_url ],
      #   include: {
      #     blog_category: { only: [ :title ] },
      #     milk_admin: { only: [ :email ] }
      #   }
      # )}
    end
  end

  # GET /milk_admin/blogs/dashboard
  #
  # Shows the blogs dashboard with metrics and blog list
  def dashboard
    @blogs = Blog.all.sorted
    @featured_blog = Blog.where(featured: true).first
    @total_blogs = Blog.count
    @published_blogs = Blog.published.count
    @draft_blogs = Blog.draft.count
    @scheduled_blogs = Blog.scheduled.count
    @total_views = Blog.sum(:views_count)
    @top_viewed_blogs = Blog.published.order(views_count: :desc).limit(10)

    if @featured_blog.present?
      @blogs = @blogs.where.not(id: @featured_blog.id)
    end

    render layout: false if turbo_frame_request?
  end

  # GET /milk_admin/blogs/new
  #
  # Initializes a new Blog object.
  # The `new` action is used to display a form for creating a new blog post.

  def new
    @blog = Blog.new
    render layout: false if turbo_frame_request?
  end

  def edit
    render layout: false if turbo_frame_request?
  end

  # POST /milk_admin/blogs
  #
  # Creates a new blog post using provided blog parameters.
  # Associates the blog post with the current milk admin.
  #
  # On success:
  # - Sets the image URL if an image is attached.
  # - Redirects to the blogs listing page with a success notice.
  # - Renders the blog as JSON with a 201 status code.
  #
  # On failure:
  # - Renders the new blog form with an unprocessable entity status.
  # - Renders the errors as JSON with an unprocessable entity status.

  def create
    @blog = Blog.new(blog_params)
    @blog.milk_admin_id = current_milk_admin.id

    respond_to do |format|
      if @blog.save
        @blog.process_body  # Call process_body to ensure TOC and body are updated
        redirect_path = turbo_frame_request? ? milk_admin_blogs_dashboard_path : milk_admin_blogs_path
        format.html { redirect_to redirect_path, notice: "Blog was successfully created." }
        format.json { render json: @blog }
      else
        format.html do
          render :new, status: :unprocessable_entity, layout: !turbo_frame_request?
        end
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /milk_admin/blogs/1
  #
  # Updates a blog using the given blog parameters.
  # Associates the blog post with the current milk admin.
  #
  # On success:
  # - Sets the image URL if an image is attached.
  # - Redirects to the blogs listing page with a success notice.
  # - Renders the blog as JSON with a 201 status code.
  #
  # On failure:
  # - Renders the new blog form with an unprocessable entity status.
  # - Renders the errors as JSON with an unprocessable entity status.
  def update
    @blog.milk_admin_id = current_milk_admin.id
    respond_to do |format|
      if @blog.update(blog_params)
        @blog.process_body  # Call process_body to ensure TOC and body are updated
        redirect_path = turbo_frame_request? ? milk_admin_blogs_dashboard_path : milk_admin_blogs_path
        format.html { redirect_to redirect_path, notice: "Blog was successfully updated." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html do
          render :new, status: :unprocessable_entity, layout: !turbo_frame_request?
        end
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milk_admin/blogs/1
  #
  # Destroys a blog and any associated image.
  #
  # On success:
  # - Redirects to the blogs listing page with a success notice.
  # - Renders the blog as JSON with a 204 status code.
  #
  # On failure:
  # - Renders the new blog form with an unprocessable entity status.
  # - Renders the errors as JSON with an unprocessable entity status.
  def destroy
    respond_to do |format|
      if @blog.destroy
        redirect_path = turbo_frame_request? ? milk_admin_blogs_dashboard_path : milk_admin_blogs_path
        format.html { redirect_to redirect_path, status: :see_other, notice: "Blog and image were successfully destroyed." }
        format.json { head :no_content }
      else
        redirect_path = turbo_frame_request? ? milk_admin_blogs_dashboard_path : milk_admin_blogs_path
        format.html { redirect_to redirect_path, alert: "Failed to destroy the blog." }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /milk_admin/blogs/1/destroy_image
  #
  # Destroys the associated image from the blog.
  #
  # On success:
  # - Redirects to the edit page of the blog with a success notice.
  # - Renders the blog as JSON with a 204 status code.
  #
  # On failure:
  # - Renders the edit page of the blog with an unprocessable entity status.
  # - Renders the errors as JSON with an unprocessable entity status.
  def destroy_image
    @blog.blog_image.purge_later

    respond_to do |format|
      if @blog.blog_image.attached?
        format.html { redirect_to edit_milk_admin_blog_path(@blog) }
        format.turbo_stream { render turbo_stream: turbo_stream.remove(dom_id(@blog, "blog_image")) }
      else
        format.html { redirect_to edit_milk_admin_blog_path(@blog), alert: "No image to remove." }
      end
    end
  end

  private

  # Strong parameters method for blog attributes.
  #
  # Ensures only the permitted attributes are allowed from the params hash.
  #
  # @return [ActionController::Parameters] filtered parameters for creating or updating a blog.

  def blog_params
    params.require(:blog).permit(:blog_image,
                                 :title,
                                 :subtitle,
                                 :content,
                                 :published_at,
                                 :milk_admin_id,
                                 :processed_body,
                                 :featured,
                                 :blog_category_id)
  end

  # Sets the @blog_categories instance variable.
  #
  # This method is called by the before_action callback in the BlogController,
  # This method retrieves all blog categories from the database,
  # orders them by their title, and assigns them to the @blog_categories
  # instance variable for use in views or other controller actions.

  def set_blog_categories
    @blog_categories = BlogCategory.all.order(:title)
  end

  # Finds the blog with the given id and assigns it to the @blog instance variable.
  #
  # This method is called by the before_action callback in the BlogController and
  # is used by multiple actions in the controller to fetch the blog related to
  # the current request.
  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/milk_admin/contacts_controller.rb
class MilkAdmin::ContactsController < ApplicationController
  before_action :authenticate_milk_admin!

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy
    redirect_to milk_admin_root_path, notice: "Message was successfully deleted."
  end
end

app/controllers/milk_admin/messages_controller.rb
# Messages Controller for Milk Admin
class MilkAdmin::MessagesController < ApplicationController
  before_action :authenticate_milk_admin!

  def dashboard
    @contacts = Contact.order(created_at: :desc)

    render layout: false if turbo_frame_request?
  end
end

app/controllers/milk_admin/pills_controller.rb
class MilkAdmin::PillsController < ApplicationController
  before_action :authenticate_milk_admin!
  before_action :set_pill, only: [ :edit, :update, :destroy ]
  before_action :set_colors_groups, only: [ :new, :edit, :update ]

  def index
    @pills = Pill.all.group_by(&:group)
    @plain_pills = Pill.all

    respond_to do |format|
      format.html
      format.json { render json: @plain_pills.as_json(only: [ :id, :group, :skill, :version, :version_color ]) }
    end
  end

  def new
    @pill = Pill.new
  end

  def create
    @pill = Pill.new(pill_params)

    if @pill.save
      redirect_to pills_path, notice: "Pill was successfully created."
    else
      render :new
    end
  end

  def edit; end

  def update
    if @pill.update(pill_params)
      redirect_to pills_path, notice: "Pill was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @pill.destroy
    redirect_to pills_path, notice: "Pill was successfully destroyed."
  end

  private

  def pill_params
    params.require(:pill).permit(:skill, :version, :group, :version_color, :resume_id)
  end

  def set_pill
    @pill = Pill.find(params[:id])
  end

  def set_colors_groups
    @colors_groups = Pill.pluck(:version_color, :group).uniq.sort
  end
end

app/controllers/milk_admin/profiles_controller.rb
# Profile Controller for Milk Admin
class MilkAdmin::ProfilesController < ApplicationController
  # Ensure milk admin is logged in
  before_action :authenticate_milk_admin!
  before_action :set_profile

  # GET /milk_admin/profile
  def show
    render layout: false if turbo_frame_request?
  end

  # GET /milk_admin/profile/edit
  def edit
    render layout: false if turbo_frame_request?
  end

  # PATCH/PUT /milk_admin/profile
  def update
    if @profile.update(profile_params)
      redirect_to milk_admin_profile_path, notice: "Profile was successfully updated."
    else
      render :edit, status: :unprocessable_entity, layout: !turbo_frame_request?
    end
  end

  private

  def set_profile
    @profile = current_milk_admin.profile || current_milk_admin.create_profile
  end

  def profile_params
    params.require(:milk_admin_profile).permit(
      :first_name,
      :last_name,
      :bio,
      :avatar,
      social_links: {}
    )
  end
end

app/controllers/milk_admin/tasks_controller.rb
# app/controllers/milk_admin/tasks_controller.rb

class MilkAdmin::TasksController < ApplicationController
  before_action :authenticate_milk_admin!
  before_action :set_project
  before_action :set_task, only: [ :edit, :update, :destroy ]

  # POST /milk_admin/projects/1/tasks
  def create
    @task = @project.tasks.build(task_params)

    if @task.save
      redirect_to milk_admin_project_path(@project), notice: "Task created."
    else
      # If it fails, we re-render the project's show page
      # We need to load all the other variables that show page needs
      @tasks = @project.tasks.order(:created_at)
      @progress = @project.progress_percentage.round
      @progress_time = @project.progress_percentage_by_time

      # Now render the 'show' template from the 'projects' controller
      render "milk_admin/projects/show", status: :unprocessable_entity
    end
  end

  # GET /milk_admin/projects/1/tasks/1/edit
  def edit
    # @project and @task are already set
  end

  # PATCH/PUT /milk_admin/projects/1/tasks/1
  def update
    if @task.update(task_params)
      redirect_to milk_admin_project_path(@project), notice: "Task updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /milk_admin/projects/1/tasks/1
  def destroy
    @task.destroy
    redirect_to milk_admin_project_path(@project), notice: "Task deleted.", status: :see_other
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = @project.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :estimated_time, :completed)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects/index (public)
  def index
    @projects = Project.where(featured: false)
  end
end

app/helpers/milk_admin_helper.rb
module MilkAdminHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/milk_admin/projects/dashboard.html.erb
<%= turbo_frame_tag "dashboard_content" do %>
  <%= render "shared/admin_breadcrumbs", breadcrumbs: [{ name: "Projects" }] %>

  <!-- Header with Actions -->
  <div class="flex items-center justify-between mb-6">
    <h2 class="text-3xl font-bold text-gray-900">Projects</h2>
    <%= link_to new_milk_admin_project_path, data: { turbo_frame: "dashboard_content" }, class: "inline-flex items-center gap-2 px-5 py-3 bg-sky-700 hover:bg-sky-600 text-white rounded-lg font-medium transition-colors" do %>
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
      </svg>
      New Project
    <% end %>
  </div>

  <!-- Featured Projects -->
  <% if @featured_projects.any? %>
    <% @featured_projects.each do |f_project| %>
      <div class="bg-gradient-to-r from-yellow-50 to-orange-50 rounded-lg shadow-sm border-2 border-yellow-400 mb-6 p-6">
        <div class="flex items-start gap-4">
          <svg class="w-8 h-8 text-yellow-500 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
          </svg>
          <div class="flex-1">
            <h4 class="text-xl font-bold text-gray-900 mb-2"><%= f_project.title %></h4>
          </div>
          <div class="flex items-center gap-2">
            <%= link_to root_path, class: "p-2 text-gray-600 hover:text-gray-900 hover:bg-white rounded-lg transition-colors" do %>
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"></path>
              </svg>
            <% end %>
            <%= link_to root_path, class: "p-2 text-sky-600 hover:text-sky-900 hover:bg-white rounded-lg transition-colors" do %>
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
              </svg>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/milk_admin/projects/edit.html.erb
<div class="flex flex-col justify-center items-center w-full mt-4">
  <div class="w-fit bg-slate-800 rounded-md p-4">
    <h1 class="text-3xl text-sky-100 align-middle text-center bg-sky-900 rounded-md mb-2 p-2">Edit Project</h1>
    <div>
      <%= render partial: "milk_admin/projects/partial/form", locals: { project: @project } %>
    </div>
  </div>
</div>

app/views/milk_admin/projects/index.html.erb
<%= turbo_frame_tag "dashboard_content" do %>
  <%= render "shared/admin_breadcrumbs", breadcrumbs: [{ name: "Projects" }] %>

  <!-- Header with Actions -->
  <div class="flex items-center justify-between mb-6">
    <h2 class="text-3xl font-bold text-gray-900">Projects</h2>
    <%= link_to new_milk_admin_project_path, data: { turbo_frame: "dashboard_content" }, class: "inline-flex items-center gap-2 px-5 py-3 bg-sky-700 hover:bg-sky-600 text-white rounded-lg font-medium transition-colors" do %>
      <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"></path>
      </svg>
      New Project
    <% end %>
  </div>

  <!-- Featured Projects -->
  <% if @featured_projects.any? %>
    <% @featured_projects.each do |f_project| %>
      <div class="bg-gradient-to-r from-yellow-50 to-orange-50 rounded-lg shadow-sm border-2 border-yellow-400 mb-6 p-6">
        <div class="flex items-start gap-4">
          <svg class="w-8 h-8 text-yellow-500 flex-shrink-0 mt-1" fill="currentColor" viewBox="0 0 20 20">
            <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z"></path>
          </svg>
          <div class="flex-1">
            <h4 class="text-xl font-bold text-gray-900 mb-2"><%= f_project.title %></h4>
          </div>
          <div class="flex items-center">
            <%= link_to milk_admin_project_path(f_project), class: "p-2 text-sky-600 hover:text-sky-900 hover:bg-white rounded-lg transition-colors" do %>
              <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
              </svg>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/milk_admin/projects/new.html.erb
<div class="flex flex-col justify-center items-center w-full mt-4">
  <div class="w-fit p-4">
    <h1 class="text-3xl text-sky-100 align-middle text-center bg-sky-900 rounded-md mb-2 p-2">Create a new Project</h1>
    <div class="bg-slate-800 rounded-md my-2">
      <%= render partial: "milk_admin/projects/partial/form", locals: { project: @project } %>
      
    </div>
  </div>
</div>

app/views/milk_admin/projects/show.html.erb
<%= turbo_frame_tag "dashboard_content" do %>
  <%= render "shared/admin_breadcrumbs", breadcrumbs: [ 
    { name: "Projects", url: milk_admin_projects_path },
    { name: "Show: #{@project.title}" } 
  ] %>

  <div class="flex ">
  </div>
  <h1><%= @project.title %> Dashboard</h1>

  <p>Progress (by count): <%= @progress %>%</p>
  <p>Progress (by time): <%= @progress_time %>%</p>

  <hr>

  <h2>New Task</h2>
  <%# This form talks to your new TasksController! %>
  <%= form_with(model: [:milk_admin, @project, @task]) do |form| %>
    
    <%# Error messages %>
    <% if @task.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>
        <ul>
          <% @task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
    
    <div>
      <%= form.label :description %>
      <%= form.text_area :description, rows: 5 %>
    </div>

    <div>
      <%= form.label :status %>
      <%= form.select :status, ["To Do", "In Progress", "Done"] %>
    </div>
    
    <div>
      <%= form.label :estimated_time, "Estimated Time (hours)" %>
      <%= form.number_field :estimated_time %>
    </div>

    <div class="border-2 border-red-600 rounded p-2">
      <%= form.submit %>
    </div>
  <% end %>

  <hr>

  <h2>All Tasks</h2>
  <div id="tasks">
    <% @tasks.each do |task| %>
      <div>
        <h3><%= task.title %></h3>
        <p><%= task.description %></p>
        <p>
          <strong>Status:</strong> <%= task.status %> | 
          <strong>Time:</strong> <%= task.estimated_time %> hours
        </p>
        <%= link_to "Edit", edit_milk_admin_project_task_path(@project, task) %>
        <%= button_to "Delete", milk_admin_project_task_path(@project, task), method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      <hr>
    <% end %>
  </div>
<% end %>